spring.application.name=realizaemailservice

server.port=8080

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=email origem
spring.mail.password=autenticacao necessaria email origem
mail.to=email destino

