spring.application.name=realizaemailservice

spring.mail.host=smtp.gmail.com
spring.mail.port=587

//Variaveis devem ser inseridas pelo arquivo application-demo

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_APP_PASSWORD}
mail.to=${MAIL_TO}

//Profile ativa para uso local

spring.profiles.active=demo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

