spring.application.name=realizaemailservice

spring.mail.host=smtp.gmail.com
spring.mail.port=587

--------------------- Para testar, precisa configurar um servidor SMTP e ter um email de destino para receber os emails. ---------------------

spring.mail.username=Insira email de origem, o qual pertence ao servidor SMTP configurado, aqui
spring.mail.password=Insira sua senha do email de origem aqui
mail.to=Insira o email de destino aqui, email que recebra as mensagems de teste

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

