spring.application.name=realizaemailservice

spring.mail.host=smtp.gmail.com
spring.mail.port=587

SPRING_MAIL_USERNAME=caldeirariarealiza@gmail.com
SPRING_MAIL_PASSWORD=oahm swxb zbrg gjsi
SPRING_MAIL_TO=contato@caldeirariarealiza.com.br

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
