spring.application.name=realizaemailservice

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME:dummy}
spring.mail.password=${MAIL_APP_PASSWORD:dummy}
mail.to=${MAIL_TO:dummy@test.com}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

