spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=caldeirariarealiza@gmail.com
spring.mail.password=oahm swxb zbrg gjsi
mail.to=contato@caldeirariarealiza.com.br

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

server.tomcat.max-http-post-size=52428800
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB